import streamlit as st
import joblib
import numpy as np

# ----------------- PAGE CONFIG -----------------
st.set_page_config(
    page_title="AI vs Human Detector",
    page_icon="🤖",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# ----------------- DARK MODE CSS -----------------
dark_css = """
<style>
body { background-color: #0e1117; color: #fafafa; }

.stTextArea textarea {
    background-color: #161a23 !important;
    color: #ffffff !important;
    border: 1px solid #30363d !important;
    border-radius: 8px !important;
}

.stButton>button {
    background-color: #30363d !important;
    color: white !important;
    border-radius: 8px !important;
    padding: 10px 18px;
    border: 1px solid #444 !important;
    transition: 0.2s;
}
.stButton>button:hover {
    background-color: #238636 !important;
    border: 1px solid #238636 !important;
    transform: scale(1.05);
}

.result-box {
    padding: 20px;
    background-color: #161b22;
    border-radius: 10px;
    border: 1px solid #30363d;
}

.bar-good {
    background-color: #2ea043;
    height: 20px;
    border-radius: 5px;
}
.bar-bad {
    background-color: #f85149;
    height: 20px;
    border-radius: 5px;
}
</style>
"""
st.markdown(dark_css, unsafe_allow_html=True)

# ----------------- LOAD MODEL -----------------
model = joblib.load("ai_detector_model.pkl")
vectorizer = joblib.load("tfidf_vectorizer.pkl")

# ----------------- HEADER -----------------
st.markdown("<h1 style='text-align:center;'>🤖 AI vs Human Text Detector</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center;color:#9ca3af;'>Check if the given text is written by a human or generated by AI.</p>", unsafe_allow_html=True)

# ----------------- INPUT AREA -----------------
user_input = st.text_area("Enter text below:", height=200)

if st.button("🔍 Detect"):
    if not user_input.strip():
        st.warning("Please enter some text.")
    else:
        X = vectorizer.transform([user_input])
        prob = model.predict_proba(X)[0]
        pred = model.predict(X)[0]

        ai_prob = float(prob[1])
        human_prob = float(prob[0])

        st.markdown("<div class='result-box'>", unsafe_allow_html=True)

        if pred == 1:
            st.markdown("<h3 style='color:#f85149;'>⚠️ AI-Generated Text</h3>", unsafe_allow_html=True)
        else:
            st.markdown("<h3 style='color:#2ea043;'>✅ Human-Written Text</h3>", unsafe_allow_html=True)

        st.write("### 🔢 Probability Scores")

        st.write(f"**Human: {human_prob*100:.2f}%**")
        st.markdown(f"<div class='bar-good' style='width:{human_prob*100}%;'></div>", unsafe_allow_html=True)

        st.write("")
        st.write(f"**AI: {ai_prob*100:.2f}%**")
        st.markdown(f"<div class='bar-bad' style='width:{ai_prob*100}%;'></div>", unsafe_allow_html=True)

        st.markdown("</div>", unsafe_allow_html=True)
